-- MySQL Script generated by MySQL Workbench
-- 12/12/20 01:51:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pizza_website
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza_website
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizza_website` DEFAULT CHARACTER SET utf8 ;
USE `pizza_website` ;

-- -----------------------------------------------------
-- Table `pizza_website`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_website`.`product_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(128) NULL,
  `description` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza_website`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_website`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `description` VARCHAR(255) NULL,
  `price` VARCHAR(45) NULL,
  `image` VARCHAR(255) NULL,
  `product_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_type_id`),
  INDEX `fk_product_product_type_idx` (`product_type_id` ASC),
  CONSTRAINT `fk_product_product_type`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `pizza_website`.`product_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
